- hosts: localhost
  tasks:
  - name: Deploy the service
    community.kubernetes.k8s:
      state: present
      #  src: /home/ubuntu/shyla-pet/service.yml
      definition: "{{ lookup('file', '/home/ubuntu/shyla-pet/service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the application
    community.kubernetes.k8s:
      state: present
      src: /home/ubuntu/shyla-pet/deployment.yml
      validate_certs: no
      namespace: default
      # definition: ""
