- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s_raw:
      state: present
      src: /var/lib/jenkins/workspace/test/service.yml
      #definition: "{{ lookup('file', '/var/lib/jenkins/workspace/test/service.yml') | from_yaml }}"
      #   - name: Deploy the application
#     community.kubernetes.k8s:
#       state: present
#       src: /var/lib/jenkins/workspace/test/deployment.yml
#       validate_certs: no
#       namespace: default
#       # definition: ""
