- hosts: localhost
  tasks:
  - name: Deploy the service
    k8s_raw:
      name: test-svc
      state: present
      #  src: /home/ubuntu/shyla-pet/service.yml
      definition: "{{ lookup('file', '/var/lib/jenkins/workspace/test/service.yml') | from_yaml }}"
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s_raw:
      state: present
      src: /var/lib/jenkins/workspace/test/deployment.yml
      validate_certs: no
      namespace: default
      # definition: ""
