- hosts: localhost
  vars:
    ansible_python_interpreter: /usr/bin/python2.7
  tasks:
  - name: Deploy the service
    k8s:
      state: present
      src: service.yml
      validate_certs: no
      namespace: default
  - name: Deploy the application
    k8s:
      src: deployment.yml
      state: present
      validate_certs: no
      namespace: default
